apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: logging
spec:
  capacity:
    storage: 2000Mi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.1.0.54
    path: /data/es
